### ISSUE TITLE
Fix ossec::server bombing when there is no node['fqdn']

### ISSUE THREAD

**Issue by bknowles** [sous-chefs/ossec#23]
I'm putting together a PR to fix this issue.  Thanks!

**Comment by tas50** [comment]
I'm pretty sure we've resolved our issues with FQDNs in the chef-client itself so you should always have a FQDN at this point. It doesn't require the node to converge. It just needs Ohai to run, which is part of the chef-client run. I'm pretty sure we can close this out at this point.

**Comment by damacus** [comment]
This one looks like it's fixed now. If I'm wrong please do reopen! 

Thanks,
Dan
