### ISSUE TITLE
ossec-wazuh fork

### ISSUE THREAD

**Issue by necrose99** [sous-chefs/ossec#67]
Support for the fork Repos 
https://github.com/wazuh/ossec-wazuh

**Comment by josephholsten** [comment]
+1, wuzah is very useful

**Comment by josephholsten** [comment]
@necrose99 do you think you could spike a PR for this?

**Comment by necrose99** [comment]
been working in necromancy , for a few ebuilds.  for ossec/wazuh. 
I'm not all that great at ruby . but I'll be my own test victum...

**Comment by pwelch** [comment]
It looks like there is an actively maintained Wazuh cookbook already [here](https://github.com/wazuh/wazuh-chef). 

I suggest we add it as a note in the README for this cookbook instead of duplicating work.

**Comment by pwelch** [comment]
Added information to README on #96

**Comment by josephholsten** [comment]
thanks @pwelch!
