### ISSUE TITLE
Derived Attribute Issue Preventing Proper Setting Of OSSEC Server IP

### ISSUE THREAD

**Issue by toddmichael** [sous-chefs/ossec#68]
My agent `ossec.conf` file is not getting the `server-ip` discovered via search.  It appears to be a [derived attribute](https://medium.com/@samueldarwin/derived-attributes-in-chef-wrapper-cookbooks-52ea699e5d10#.cbprxn1u3) issue.... (unless it's just me).

In the attributes file we have this:

``` ruby
default['ossec']['agent_server_ip'] = nil
default['ossec']['conf']['agent']['client']['server-ip'] = node['ossec']['agent_server_ip']
```

Then in recipe space we have this:

``` ruby
node.set['ossec']['agent_server_ip'] = ossec_server.first
```

The end result of this is that `node['ossec']['conf']['agent']['client']['server-ip']` gets computed as the default value of `node['ossec']['agent_server_ip']` in attribute space (`nil`), **not** the value that it gets reassigned in recipe space.  I confirmed this by printing out the value of both attributes in my wrapper cookbook.  

There are a number of different ways to solve this.  My first inclination here is to simply dump `node['ossec']['agent_server_ip']` as it doesn't, at least at first glance, appear to be necessary.  Just use `node['ossec']['conf']['agent']['client']['server-ip']` and you avoid derived attributes.  

Appreciate it if someone could confirm or disconfirm this finding.  Once done, happy to submit a fix.  Cheers.

**Comment by toddmichael** [comment]
Apologies for that second commit reference. It was a typo.  I fixed and force pushed so that commit doesn't exist anymore, but it's still showing up here which is probably confusing.

**Comment by netflash** [comment]
LGTM

**Comment by damacus** [comment]
Cool, so I'm going to remove Chef Search when #85 is implemented. It should be much easier to set it via whatever mechanism you see fit. 
There will be some examples of how to use Chef Search with the new resource.
