### ISSUE TITLE
dist-ossec-keys.sh template not deployed due to empty ssh_hosts array

### ISSUE THREAD

**Issue by toddmichael** [sous-chefs/ossec#71]
When I converge the server in my test environment, ossec agent hosts are detected and their keys are created, but the `dist-ossec-keys.sh` template resource doesn't fire because the `ssh_hosts` array is empty.  Here's the [relevant code block](https://github.com/jtimberman/ossec-cookbook/blob/master/recipes/server.rb#L28-L43).

``` ruby
search(:node, search_string) do |n|
  ssh_hosts << n['ipaddress'] if n['keys']

  execute "#{node['ossec']['agent_manager']} -a --ip #{n['ipaddress']} -n #{n['fqdn'][0..31]}" do
    not_if "grep '#{n['fqdn'][0..31]} #{n['ipaddress']}' #{node['ossec']['dir']}/etc/client.keys"
  end
end

template '/usr/local/bin/dist-ossec-keys.sh' do
  source 'dist-ossec-keys.sh.erb'
  owner 'root'
  group 'root'
  mode 0755
  variables(ssh_hosts: ssh_hosts.sort)
  not_if { ssh_hosts.empty? }
end
```

I was able to get it to work by making the following change:

``` ruby
-  ssh_hosts << n['ipaddress'] if n['keys']
+  ssh_hosts << n['ipaddress'] if n.keys
```

I'm assuming here that the condition is the `keys` method, not a keys attribute as I wasn't able to find any `keys` attribute in the cookbook.

**Comment by netflash** [comment]
LGTM

**Comment by damacus** [comment]
this should go away in the next release as we're trying to get rid of chef search.
