### ISSUE TITLE
Migrate to Chef Vault

### ISSUE THREAD

**Issue by toddmichael** [sous-chefs/ossec#73]
Played with Chef Vault vs. data bags and prefer the former so I've refactored accordingly.  Always lean toward sharing with others so let me know if there's interest and I'll submit the change I've made to my fork. It's not quite ready yet only because I've replaced the latter with the former (in the interest of time), rather than coding to support both options.  Also need to update unit tests and, full disclosure, I'm not much of a unit test guy.  Only really write integration tests.  I'm willing to change though ;-)

**Comment by damacus** [comment]
We're probably going to remove the data bags in favour of custom resource blocks as they're version-able and way easier to write/maintain. 

You should still be able to feed the data from vault though!
