### ISSUE TITLE
Fix Failing CI Builds

### ISSUE THREAD

**Issue by pwelch** [sous-chefs/ossec#98]
### Cookbook version
v1.0.5/master

### Chef-client version
14.4.7

### Platform Details
Travis-CI

### Steps to Reproduce:
Running master on Travis-CI

### Expected Result:
CI builds show be passing.

### Actual Result:
Builds are failing on Travis-CI

**Comment by Sliim** [comment]
Do you plan to add unit testing in CI jobs? This is missing, all I had to do is to install required dependencies, in Gemfile:
```
group :integration do                                                                                                                                                                         
  gem 'berkshelf'
  gem 'chefspec'
end
``` 

For actual failure, I think kitchen verify on ossec service fails because it is tested inside a docker container. (Testing service status in docker is always painful..)
